name: Move new issues onto Issue triage board

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    # Skip in forks
    if: github.repository == 'element-hq/element-android'
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Issue triage
          column: Incoming
          repo-token: ${{ secrets.ELEMENT_BOT_TOKEN }}

  triage-new-issues:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/add-to-project@main
            with:
                project-url: https://github.com/orgs/element-hq/projects/91
                github-token: ${{ secrets.ELEMENT_BOT_TOKEN }}
